package com.cidic.design.model;
// Generated 2017-5-26 10:09:08 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SendEmail generated by hbm2java
 */
@Entity
@Table(name = "send_email", catalog = "design_competition_seniorman")
public class SendEmail implements java.io.Serializable {

	private Integer id;
	private String email;
	private byte sign;
	private Byte round;
	private Date createtime;

	public SendEmail() {
	}

	public SendEmail(String email, byte sign) {
		this.email = email;
		this.sign = sign;
	}

	public SendEmail(String email, byte sign, Byte round, Date createtime) {
		this.email = email;
		this.sign = sign;
		this.round = round;
		this.createtime = createtime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "email", nullable = false, length = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "sign", nullable = false)
	public byte getSign() {
		return this.sign;
	}

	public void setSign(byte sign) {
		this.sign = sign;
	}

	@Column(name = "round")
	public Byte getRound() {
		return this.round;
	}

	public void setRound(Byte round) {
		this.round = round;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

}
