$(document).ready(function(){
    $("#myForm").validate({
        ignore:[],
        rules:{
            email:{
                required:true,
                maxlength:32,
                email:true
            },
            mobile:{
                required:true,
                maxlength:18
            },
            realname:{
                required:true,
                maxlength:32
            },
            address:{
                required:true,
                maxlength:32
            },
            password:{
                required:true,
                rangelength:[6,20]
            },
            confirmPwd:{
                equalTo:"#password"
            }
        },
        messages:{
            email:{
                required:config.validErrors.required,
                maxlength:config.validErrors.maxLength.replace("${max}",32),
                email:config.validErrors.email
            },
            mobile:{
                required:config.validErrors.required,
                maxlength:config.validErrors.maxLength.replace("${max}",18)
            },
            realname:{
                required:config.validErrors.required,
                maxlength:config.validErrors.maxLength.replace("${max}",32)
            },
            address:{
                required:config.validErrors.required,
                maxlength:config.validErrors.maxLength.replace("${max}",32)
            },
            password:{
                required:config.validErrors.required,
                rangelength:config.validErrors.rangLength.replace("${max}",20).replace("${min}",6)
            },
            confirmPwd:{
                equalTo:config.validErrors.pwdNotEqual
            }
        },
        submitHandler:function(form) {
            var formObj=$(form).serializeObject();
            $.ajax({
                url:config.ajaxUrls.register,
                type:"post",
                dataType:"json",
                contentType :"application/json; charset=UTF-8",
                data:JSON.stringify(formObj),
                success:function(response){
                    if(response.success){
                        $().toastmessage("showSuccessToast",config.messages.registerSuccess);
                    }else{
                        $().toastmessage("showSuccessToast",response.message);
                    }
                },
                error:function(){
                    $().toastmessage("showSuccessToast",config.messages.networkError);
                }
            });
        }
    });
});
