$(document).ready(function(){
    var zyFormHandler=new ZYFormHandler({
        submitUrl:config.ajaxUrls.resetInfo
    });
    $("#myForm").validate({
        ignore:[],
        rules:{
            realname:{
                required:true,
                maxlength:8
            },
            address:{
                required:true,
                maxlength:32
            },
            mobile:{
                required:true
            }
        },
        messages:{
            realname:{
                required:config.validErrors.required,
                maxlength:config.validErrors.maxLength.replace("${max}",8)
            },
            address:{
                required:config.validErrors.required,
                maxlength:config.validErrors.maxLength.replace("${max}",32)
            },
            mobile:{
                required:config.validErrors.required
            }
        },
        submitHandler:function(form) {
            zyFormHandler.submitFormWithJSON(form);
        }
    });
});
