$(document).ready(function(){
    var zyFormHandler=new ZYFormHandler({
        submitUrl:"#",
        redirectUrl:"#"
    });
    $("#myForm").validate({
        ignore:[],
        rules:{
            password:{
                required:true,
                rangelength:[6,20]
            },
            confirmPwd:{
                equalTo:"#password"
            }
        },
        messages:{
            password:{
                required:config.validErrors.required,
                rangelength:config.validErrors.rangLength.replace("${max}",20).replace("${min}",6)
            },
            confirmPwd:{
                equalTo:config.validErrors.pwdNotEqual
            }
        },
        submitHandler:function(form) {
            zyFormHandler.submitFormWithPS(form);
        }
    });
});
