document.write(['<ul class="menu">',

        '<li class="item" data-page-name="news">',
            '<span class="glyphicon glyphicon-file"></span>',
            '<a class="link" href="views/backend/newsMgr.html">新闻</a>',
        '</li>',

        '<li class="item" data-page-name="judge">',
            '<span class="glyphicon glyphicon-file"></span>',
            '<a class="link" href="views/backend/judgeMgr.html">评委</a>',
        '</li>',
        '<li class="item" data-page-name="works">',
            '<span class="glyphicon glyphicon-th-list"></span>',
            '<a class="link" href="views/backend/worksMgr.html">作品</a>',
        '</li>',
        '<li class="item" data-page-name="user">',
            '<span class="glyphicon glyphicon-user"></span>',
            '<a class="link" href="views/backend/userMgr.html">用户</a>',
        '</li>',
        '<li class="item" data-page-name="setting">',
            '<span class="glyphicon glyphicon-cog"></span>',
            '<a class="link" href="views/backend/setting.html">设置</a>',
        '</li>',
        '<li class="item">',
            '<span class="glyphicon glyphicon-th-list"></span>',
            '<a class="link">子菜单</a>',
            '<span class="glyphicon glyphicon-chevron-down rightIcon"></span>',
            '<ul class="subMenu">',
                '<li class="sItem">',
                    '<span class="circle">原点</span>',
                    '<a class="sLink" href="#">子菜单1</a>',
                '</li>',
                '<li class="sItem">',
                    '<span class="circle">原点</span>',
                    '<a class="sLink" href="#">子菜单2</a>',
                '</li>',
                '<li class="sItem">',
                    '<span class="circle">原点</span>',
                    '<a class="sLink" href="#">子菜单3</a>',
                '</li>',
            '</ul>',
        '</li>',
    '</ul>'].join(""));